name: publish
on:
  push:
    branches:
      - main
jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    strategy:
      matrix:
        node-version: [ 22 ]
    steps:
      - uses: Kesin11/actions-timeline@v2
      - run: |
          git config --global user.email "me@shu.nu"
          git config --global user.name "Shun Ueda"
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          registry-url: https://registry.npmjs.org
      - run: corepack enable
      - uses: pnpm/action-setup@v4
      - run: corepack enable
      - run: pnpm install --frozen-lockfile
      - run: pnpm build
      - run: pnpm version patch
      - run: pnpm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NODE_AUTH_TOKEN }}
      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: release ${{ github.event.release.tag_name }}"
          branch: ${{ github.event.repository.default_branch }}
          file_pattern: package.json
